print("Welcome to AI Applications!")
name = input("What is your name? ")
print("Hello", name, "It's great to meet you! ")
fav = input("What is your favorite programming language? ")
print("Awesome, ", name , "! ", fav, "is a great choice!")